name: Bug Report
description: Create a report to help us improve.
title: "[Bug] "
labels: [ "bug" ]
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: |
        Please check that you have done the following things before submitting an issue.
      options:
        - label: I confirm that I have [searched for existing issues / pull requests](https://github.com/Xujiayao/TextPlaceholderAPI-Compat/issues?q=) before reporting to avoid duplicate reporting.
          required: true
        - label: I confirm that I am reporting compatibility issues of Placeholder API Compat, instead of issues related to the Placeholder API library itself.
          required: true
        - label: I confirm that I noted that if I don't follow the instructions, the issue may be closed directly.
          required: true
  - type: dropdown
    id: minecraft_version
    attributes:
      label: Minecraft Version
      description: |
        The version of Minecraft you are using?
        If a version is not listed below, it is not supported by Placeholder API Compat.
      multiple: false
      options:
        - "1.21.5"
        - "1.21.4"
        - "1.21.3"
        - "1.21.2"
        - "1.21.1"
        - "1.21"
    validations:
      required: true
  - type: dropdown
    id: placeholder_api_compat_version
    attributes:
      label: Placeholder API Compat Version
      description: |
        The version of Placeholder API Compat you are using?
      multiple: false
      options:
        - "Latest Build (GitHub Actions)"
        - "2.6.1-compat.1"
        - "2.5.2-compat.1"
        - "2.5.1-compat.2"
        - "2.5.1-compat.1"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please tell us what the bug is with a clear and detailed description, add screenshots to help explain.
    validations:
      required: true
  - type: textarea
    id: to_reproduce
    attributes:
      label: To Reproduce
      description: |
        How do you trigger this bug? Please walk us through it step by step.
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
      description: |
        Please provide your FULL log (/log/latest.log file) here.
      render: text
    validations:
      required: true
